### ISSUE TITLE
module.controllers.google_compute_instance.controllers: 1 error(s) occurred:

### ISSUE THREAD

**Issue by unfii** [poseidon/terraform-google-kubernetes#1]
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.google_compute_zones.all: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.controllers.google_compute_instance.controllers: 1 error(s) occurred:

* module.controllers.google_compute_instance.controllers: element: element() may not be used with an empty list in:

${element(data.google_compute_zones.all.names, count.index)}

**Comment by dghubble** [comment]
Sorry, I didn't see this. This is a mirror of the development repo https://github.com/poseidon/typhoon

**Comment by dghubble** [comment]
This looks quite familiar and it should be solved now (I can't repro). If not, lemme know the region and I'll take a look.
